<?php

return [
    'baseUrl' => '/web/',
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'rules' => [
        '' => 'site/default/index',
        'admin' => 'admin/default/index',
        'admin/login' => 'site/profile/default/login',
        'admin/logout' => 'site/profile/default/logout',
        'page/<slug>' => 'site/page/slug',
        'category/<id>' => 'site/category/index',
        'product/<id>' => 'site/product/index',
        'service/<id>' => 'site/service/index',
        'cart' => 'site/cart/index',
        'cart/order' => 'site/cart/order',
        'cart/checkout' => 'site/cart/checkout',
        'pricelist/product' => 'site/pricelist/product',
        'profile' => 'site/profile/default/index',
        'profile/login' => 'site/profile/default/login',
        'profile/logout' => 'site/profile/default/logout',
        'profile/register' => 'site/profile/default/register',
        'profile/register-provider'=>'site/profile/default/register-provider',
        'profile/forgot-request' => 'site/profile/default/forgot-request',
        'profile/forgot-change' => 'site/profile/default/forgot-change',
        'profile/message' => 'site/profile/default/message',
        'profile/<_u:[\w\-]+>/personal' => 'site/profile/<_u>/default/personal',
        'profile/<_u:[\w\-]+>/email' => 'site/profile/<_u>/default/email',
        'profile/<_u:[\w\-]+>/order' => 'site/profile/<_u>/default/order',
        'profile/<_u:[\w\-]+>/becomeprovider'=>'site/profile/<_u>/default/becomeprovider',
        'profile/<_c:[\w\-]+>/<_a:[\w\-]+>' => 'site/profile/<_c>/<_a>',
        'profile/<_c:[\w\-]+>' => 'site/profile/<_c>/index',
        'profile/<_u:[\w\-]+>/<_c:[\w\-]+>/<_a:[\w\-]+>' => 'site/profile/<_u>/<_c>/<_a>',
        //'<_m:[\w\-]+>' => '<_m>/default/index',
        '<_c:[\w\-]+>/<id:\d+>' => '<_c>/default/view',
    ],
];
